version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/watchwave_api
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # environment:
    #   - DJANGO_SETTINGS_MODULE=watchwave_api.settings.dev
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=watchwave_db
