# Generated by Django 5.0.3 on 2024-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
